name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Release
        run: |
          gh release create ${{ github.ref }} --generate-notes -t ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}